#!/bin/bash

set -e

INSTALL_DIR="/usr/local/bin"

_sudo_if_need() {
  local command="$1"
  if [ -w $INSTALL_DIR ]; then
    bash -c "${command}"
  else
    bash -c "sudo ${command}"
  fi
}

_join() {
  local arg
  printf "%s" "$1"
  shift
  for arg in "$@"; do
    printf " "
    printf "%s" "${arg// /\ }"
  done
}

_echo() {
  printf "${tty_blue}==>${tty_bold} %s${tty_reset}\n" "$(_join "$@")"
}

_sudo_if_need "rm -rf $INSTALL_DIR/tuist"

_echo "xcpnc uninstalled"
